### ISSUE TITLE
Update Docsy for Swagger feature

### ISSUE THREAD

**Issue by alexearnshaw** [Axway/axway-open-docs#106]
Docsy has a new feature for displaying Swagger API docs, which could be used to display any swagger we have for APIs instead of needing to link to them in apidocs.axway.com or stoplight?
TBC if it supports only open api 3.0 or also 2.0

**Comment by alexearnshaw** [comment]
I attempted to do this on Friday but kept having problems with submodules and with Hugo version, so blocking for now.

**Comment by andreamussap** [comment]
Closed - For more information, see RMF-187
