### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by markbice** [Axway/axway-open-docs#129]
When I'm using this page (ie, trying to read/follow it) I am a bit confused if this is one process, or 3 different ways yo provide feedback and/or make suggested changes?

https://axway-open-docs.netlify.com//docs/contribution_guidelines/

The **Edit a page on GitHub**... and the **Create an issue on GitHub**... and the Edit with Netlify CMS... all seem to different paths for different types of feedback. Is it possible to clarify this better?

**Comment by andreamussap** [comment]
@markbice Thanks for the feedback. I've made some updates and I believe the procedure is clearer now. Can you please have a look and let me know your thoughts?

**Comment by andreamussap** [comment]
**Pull request** https://github.com/Axway/axway-open-docs/pull/130

**Comment by markbice** [comment]
Yes, I like that is it much clearer. I think Rober Eng stumbled across this same confusion earlier.  Thanks for the prompt response.

**Comment by markbice** [comment]
FYI, Do I need to close the issue, or is that in your hands now?

**Comment by andreamussap** [comment]
Thanks, Mark.
I can close the issue. 
Have a nice weekend.
/Andrea
