### ISSUE TITLE
[DOC] Update contrib guidelines with recommendation to delete old forks

### ISSUE THREAD

**Issue by alexearnshaw** [Axway/axway-open-docs#139]
## Issue description

When a user edits a page for the first time, a fork is created. If they come back a few weeks later to make another edit, the same fork is used, but Axway master is then many commits ahead, meaning that the user might edit an outdated version of a page, and then get many conflicts when they try to merge their fork with Axway master via PR.  

On Github UI there is no simple way to sync the fork with Axway master, so we need to advise users to delete their fork and allow it to be recreated when they edit a new page.

There is a way to sync a fork via CLI but we should assume most users will not use CLI. 

Also Netlify CMS has this same issue but as the CMS displays content from Axway master instead of user's fork, it probably won't be as much an issue (but conflicts could still occur at merge time?)

## Problem location

https://axway-open-docs.netlify.com/docs/contribution_guidelines/

## Suggestions for a fix

Update the guidelines with instructions for users to delete forks and recommend that they delete forks older than X days.

**Comment by alexearnshaw** [comment]
https://github.com/isaacs/github/issues/121

**Comment by andreamussap** [comment]
PR https://github.com/Axway/axway-open-docs/pull/141
