### ISSUE TITLE
[DOC] Add more use cases to contrib guidelines

### ISSUE THREAD

**Issue by alexearnshaw** [Axway/axway-open-docs#150]
## Issue description

I don't think users are fully aware how to:

1. Make additional edits to their existing PRs
2. Make contributions that are new topics rather than edits to existing topics

## Problem location

https://axway-open-docs.netlify.com/docs/contribution_guidelines/

## Suggestions for a fix

Add some guidance for both of the above use cases to the procedures for both Edit on Github and Edit on CMS

**Comment by andreamussap** [comment]
**Blocker** - I've started to work on this Issue, but when I tried to build the site locally:

```
amussap@ITEM-AX31566 MINGW64 ~/axway-open-docs (master)
$ hugo server
Building sites … ERROR 2020/03/02 14:03:27 error: failed to transform resource: POSTCSS: failed to transform "scss/cms.css" (text/css): PostCSS not found; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/
Total in 2953 ms
Error: Error building site: logged 1 error(s)
```

The error happens both in Ubuntu and in GitBash (Windows).

- In Ubuntu, I've deleted and recloned axway Git project, and the error persists.
- I've reinstalled Hugo. The error persists.
- I didn't find anything related on Google yet. Will keep looking.

**Comment by alexearnshaw** [comment]
@andreamussap one more comment relating to this issue - PR #460 currently only addresses the new use cases for the CMS, but I think it would certainly be useful to describe the "edit existing" use case for Github UI also (creating new via Github UI is not at all easy so can be left out), so can you either address that use case in the current PR or create a new issue for adding that use case to the Github UI flow please?
