### ISSUE TITLE
Quick start installation

### ISSUE THREAD

**Issue by cbordier** [Axway/axway-open-docs#157]
The latest link in the page **API Gateway Policy Developer Guide** leads to nowhere (404 Page not found)
![image](https://user-images.githubusercontent.com/16959488/67904195-e626a000-fb2a-11e9-8b4b-719bc7a9bd9a.png)
![image](https://user-images.githubusercontent.com/16959488/67904229-fb033380-fb2a-11e9-9c6b-ae7f36c27af6.png)

In fact most of the link in the quick start installation page are not working.

**Comment by alexearnshaw** [comment]
Thank you @cbordier for opening an issue for this. 

We are currently in the process of migrating the Policy Developer Guide (#148) and when this done we will update all the links to it throughout the doc set to the correct URLs.
