### ISSUE TITLE
[DOC] (GPSFIE-615) API Manager SSO docs do not discuss certficiate validity settings in service-provider.xml

### ISSUE THREAD

**Issue by mvenzke-axway** [Axway/axway-open-docs#1872]
## Issue description

The API Manager SSO docs do not discuss the certificate validity settings for service-provider.xml

If you look at any of the sample service-provider.xml files in /apigateway/samples/sso/ you will see that there's a CertificateValidation tag with many settings that are not discussed in the docs, save for an oblique and confusing reference to the trustStorePath's default value:

truststore.jks - This is a separate truststore that is used for HTTPS communication between the SSO agent and the IdP while retrieving metadata online.

We appear to use Axway Commons SSO, which has a document on these settings on an internal URL.

I believe that we should incorporate this piece of documentation into the main API Manager SSO docs, as the Axway Commons SSO documentation is not available to customers.

## Problem location

https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_administration/apimgr_sso/saml_sso_config/index.html

## Suggestions for a fix

I don't know this area of the product particularly well so this should be reviewed by a product expert on SSO who can confirm what of the items below are applicable to APIM SSO.  I have copied below the content of the internal URL that can also be seen on GPSFIE-615 in Axway's Jira.

=====

**Certificates validation**

The SSO agent tries to validate the Service Provider and Identity Providers certificates specified in its configuration at startup. This validation is also scheduled to occur at regular intervals. At a minimum, the agent verifies the validity period of the certificates, but can also validate the full certification paths.

The certification path validation process can be configured by the CertificateValidation element in the configuration file or by calling similar methods on the configuration builder.

```
<SSOConfiguration>
    <CertificateValidation 
        pathValidation="true" 
        enableRevocation="true"
        trustStorePath=""
        trustStorePassword=""
        intermediateStorePath=""
        intermediateStorePassword=""
        delayBetweenValidations="3"
        >
        <CRLs>
            <CRL path="rev.crl"/>
            <CRL path="root.crl"/>
        </CRLs>
    </CertificateValidation>
    ...
</SSOConfiguration>
```

**pathValidation attribute**

If set to true, the certification path for each certificate will be checked. The default value is true. If set to false, the agent verifies only the validity period of each certificate.

A trust store must be specified if this attribute is true.

Intermediate certificates can be stored in a store specified by the intermediateStorePath attribute.

Intermediate certificates can also be retrieved remotely by activating the support for the Authority Information Access (AIA) extension at the JVM level, by setting the com.sun.security.enableAIAcaIssuers property to true.
enableRevocation attribute

If set to true, the agent also verifies if the certificates are not revoked.

The certificate revocation lists can be specified within the CRLs element, or by activating the support for the CRL distribution points extension at the JVM level, by setting the com.sun.security.enableCRLDP property to true.

When running with a Java 8 or greater JVM, the agent can also check a certificate revocation status by connecting to an OCSP server. To activate this functionality, set the security property ocsp.enable to true.

The certification path validation must be activated for this attribute to be taken into account.

**trustStorePath attribute**

The path to the trust store containing the trusted certificates. If this attribute is not set, the SSO agent tries to load the default JVM trust store located at $java.home/lib/security/jssecacerts or $java.home/lib/security/cacerts.

**trustStorePassword attribute**

The password to access the trust store.

**intermediateStorePath**

The path to a store containing intermediate certificates that can appear in certificate chains.

**intermediateStorePassword**

The password to access the intermediate certificates store.

**delayBetweenValidations**

Defines at which interval certificates validation occurs, in hours. Default value is 3 hours.

**Comment by ConanScott** [comment]
This is really important information and ought to be pulled to master

**Comment by mvenzke-axway** [comment]
I logged RDAPI-24389 to ask dev to review here.
