### ISSUE TITLE
[WEBSITE] Preview page is linking to main netlify.com page

### ISSUE THREAD

**Issue by cwiechmann** [Axway/axway-open-docs#214]
## Issue description
When using the preview created by netlify based on a PR some of the navigation links are pointing back to the main OpenDocs-Netlify page. With that, the preview feature is a bit difficult to use as you don't realize that switch and ultimately you miss the changes you made.

## Problem location
For instance take this preview here:
https://deploy-preview-213--axway-open-docs.netlify.com/docs/
When clicking on one of the links it goes back to:
https://axway-open-docs.netlify.com/docs/apimgr_concepts/

## Suggestions for a fix
Perhaps this is something easy to fix to generate links staying on the Preview-Domain. But, if it is super complicated I'm sure we can stay with what we have. Just wanted to report it.

**Comment by alexearnshaw** [comment]
Hi @cwiechmann 
Thanks,  we are aware of this issue but I don't think it's an easy fix unfortunately. I *think* it's something to do with the way the URL is built for the section landing pages. The links in the left navigation correctly go to the preview site, but the links in the list of topics on the page content incorrectly go to the main open docs site. The code for building the list of topics on the page comes from the Docsy theme we are using, so I'll see if they can help point us in the right direction to fix it.
