### ISSUE TITLE
Install Apache HTTP server and PHP

### ISSUE THREAD

**Issue by razvan4axway** [Axway/axway-open-docs#2270]
## Issue description

The current documentation covers the use case of installing PHP version 8. Support for PHP 8.0 has been added with the launch of Portal February 2022. Versions of Portal previous to February 2022 will fail when using the PHP 8.0 when following the documentation.
This needs to be covered to avoid issues during installations. 

## Problem location

https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_installation/apiportal_install/install_dependencies/index.html

## Suggestions for a fix

Add further documentation for previous versions of API Portal installation with supported PHP versions

**Comment by andreamussap** [comment]
This will be internally handled by the Tesla (API Portal) team. 
cc @dginevaAxway

**Comment by razvan4axway** [comment]
hi @andreamussap , thanks for that!
