### ISSUE TITLE
[DOC]Incorrect link to Transaction audit log settings

### ISSUE THREAD

**Issue by chataros** [Axway/axway-open-docs#2504]
## Issue description
Manage API Gateway events and alerts
The Events view in API Gateway Manager enables you to view and search the contents of the following in-memory gateway events and alerts:

Transaction Audit: When policy-level transaction audit logging is configured in API Gateway filters, this displays an in-memory list of transaction audit log events. A transaction audit log destination does not need to be enabled for the in-memory list of events to be updated. For more details, see [Transaction audit log settings](https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_reference/log_global_settings//index.html#transaction-audit-log-settings).

## Problem location

https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_administration/apigtw_admin/logging/index.html
under the section: "Manage API Gateway events and alerts", posted in the issue description

**Comment by andreamussap** [comment]
The issue is fixed. Thank you!
