### ISSUE TITLE
[DOC] issue in link from API Portal Nov22 release note

### ISSUE THREAD

**Issue by Cgratier** [Axway/axway-open-docs#2565]
## Issue description

The URL for "Deploy API Portal in containers" point to upgrade instructions instead of Install (https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_installation/apiportal_docker/docker_portal_upgrade/index.html). 
 

## Problem location

On  the 7.7 November 2022 release node page for API Portal (https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_relnotes/20221130_apip_relnotes/index.html)

## Suggestions for a fix

The link should point to: https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_installation/apiportal_docker/index.html

**Comment by andreamussap** [comment]
This will be fixed by RMF-365
