### ISSUE TITLE
[WEBSITE] Anchor are not present

### ISSUE THREAD

**Issue by Cgratier** [Axway/axway-open-docs#2566]
## Issue description

 The following links (anchor) are broken (nothing happens)
	- Step 1 – Configure the IdP.
	- Step 2 – Create the service-provider.xml file.

## Problem location

In the following page: https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_administration/apimgr_sso/saml_sso_config/index.html#step-1-configure-the-idp,

## Suggestions for a fix

Fix the anchor in the page.

**Comment by andreamussap** [comment]
The issue will be fixed via RMF-362
