### ISSUE TITLE
Automate review assignments and projects/labels/milestones

### ISSUE THREAD

**Issue by alexearnshaw** [Axway/axway-open-docs#261]
## Description
At the moment we are manually assigning reviewers, labels, projects, milestones to every contribution (pull requests and issues). Triaging issues when they come in is disruptive and it is not scalable as contributions grow.

We've looked at PullPanda Assigner before and it seems to be too limited for our needs. Also it does not cover label/sprojects/milestones. 

So this ticket is to research and find other ways to automate some or all of this. 

Some possible options are: 

- https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
- https://github.blog/changelog/2018-12-05-issue-template-automation-improvements/
-  https://github.com/philschatz/project-bot
- https://github.com/marketplace/pull-request-size
- https://github.com/marketplace/actions/assign-size-label

and many others in Github marketplace...

## Update

1.  We've implemented codeowners to auto assign reviewers (PR #264)
2. We're using the size label action pr-size-labeler (PR #603) but this does not work for PRs from forks
3. We've tried various other size label apps (e.g. https://github.com/marketplace/pull-request-size) and actions and they either cannot be installed or do not work on PRs from forks.
4. We also investigated https://probot.github.io/apps/mergeable/ but this was not useful either

## Still TODO

1. Investigate if https://github.com/apps/boring-cyborg can be used for automating the first contributor PR comment that links to the survey, and for labelling PRs based on the filepath so we can distinguish doc changes vs website changes.
2. Investigate if its worth asking org admin to install the size label app as this *should* work on forks https://github.com/noqcks/pull-request-size/issues/21
3. Ask org admin to remove the Mergeable app
4. Investigate if any other apps/actions can be used to add projects/milestones and other functionality e.g  https://probot.github.io/apps/

**Comment by andreamussap** [comment]
Closed - For more information, see RMF-187
