### ISSUE TITLE
[WEBSITE] Make change history on pages more useful

### ISSUE THREAD

**Issue by alexearnshaw** [Axway/axway-open-docs#273]
## Issue description

Users can see the changes that have been made to a topic in the Github meta info at the bottom of each page. However, as this is the message from the last commit, it is often not very useful to users as they want to know what content was added or removed.

## Problem location

Example: https://axway-open-docs.netlify.com/docs/apim_relnotes/20200130_apimgr_relnotes/
![image](https://user-images.githubusercontent.com/29064556/72726630-af3bb580-3b80-11ea-97ae-25573fe6ca34.png)

## Suggestions for a fix

- Agree a commit message template that is more useful to users. 
- Find out if we can use longer commit messages from Git CLI.
- Find out if there's any way to enforce a template in Git.

## Update
It seems like https://github.com/apps/boring-cyborg could be used to both enforce a PR title template and that we could use "squash & merge" to make Github use the PR title as the commit message, instead of the individual commits.

**Comment by alexearnshaw** [comment]
Came across this https://medium.com/@haydar_ai/learning-how-to-git-creating-a-longer-commit-message-16ca32746c3a

**Comment by alexearnshaw** [comment]
@andreamussap I came across this article that explains different merge strategies and think it's worth a read as it relates to this issue: https://medium.com/@elliotchance/comparison-of-merging-strategies-in-github-2f948c3b8fdc

On reading that I think we could use squash and merge instead of our current strategy (merge commit) and that this would mean that when we merge a PR we can edit the message that gets shown in the Git history (and at the bottom of each page).

**Comment by alexearnshaw** [comment]
@andreamussap I've turned squash and merge on now, so let's see how it works for the next week or two. Now you should be able to edit the merge message when merging a PR and that message is what will appear in the history/bottom of page. I'll leave this issue open for now so we can put any positive or negative comments here about how it works.

**Comment by andreamussap** [comment]
@alexearnshaw I've read the article (and other related articles) and I think we should give it a try. This will make it more meaningful when someone look at the history of the task (PR).

**Comment by alexearnshaw** [comment]
Closing this now as this seems to be working well. Example: https://axway-open-docs.netlify.app/docs/apim_installation/apigtw_install/system_requirements/ (see Github message at bottom)
