### ISSUE TITLE
Add support for variables in content

### ISSUE THREAD

**Issue by alexearnshaw** [Axway/axway-open-docs#274]
Robust variable support would allow us to use a shortcode in our Markdown source (e.g. for the product name) that gets replaced with a value from a data file at build time. 

This would make it very easy to update the docs if a product name changes and is a standard feature of most authoring tools.

- First investigate if Docsy theme has any support in this area (or plans to add any)
- If not, add this support to our own project

See https://techweb.axway.com/jira/browse/IAP-2484 for more details.

**Comment by andreamussap** [comment]
@alexearnshaw maybe as a sub-task, or related task, it might be worth to assess the docs to remove the **overuse** of the name of the products, e.g., when using `API Gateway` to simple refer to _the gateway_. Or repeating the name of the product unnecessarily: 

- Change the API Portal site logo using...
- Refresh the API Portal home page...
- You can display the name of your company in the API Portal standard footer..
- Customize a 404 error page for your API Portal....
- Refresh the API Portal home page...

We can remove the name of the product in the majority of these sentences without compromising the procedure IMHO.

**Comment by andreamussap** [comment]
Closed - See RMF-187
