### ISSUE TITLE
[DOC] Add link to K8S helm charts

### ISSUE THREAD

**Issue by alexearnshaw** [Axway/axway-open-docs#318]
## Issue description
There is no mention of K8S in APIG container doc.

## Problem location
https://axway-open-docs.netlify.com/docs/apim_installation/apigw_containers/

## Suggestions for a fix
Add a link to https://github.com/Axway/apigw-helm-charts and make it clear that these are a starting point and only supported for v7.7.0 and 7.7.0-SP1 as per email from Vinny.

The link could be added as a Q/A in this section https://axway-open-docs.netlify.com/docs/apim_installation/apigw_containers/container_getstarted/

E.g. Can you run API Gateway in Kubernetes?

**Comment by alexearnshaw** [comment]
@maherb4 Does this approach sound ok to you?

**Comment by maherb4** [comment]
Hi Alex,

Sounds perfect to me

Regards
Barry
