### ISSUE TITLE
[DOC] Alert-Boxes are not rendered properly

### ISSUE THREAD

**Issue by cwiechmann** [Axway/axway-open-docs#334]
## Issue description
The Alert-Boxes are not rendered properly. 
![image](https://user-images.githubusercontent.com/16292002/73432993-27099d00-4344-11ea-9867-8a16754e5e5c.png)
Looks like there is a hidden column wrapping The JWT Verify into it.
Same here:
![image](https://user-images.githubusercontent.com/16292002/73433060-4acce300-4344-11ea-89b9-d999b1935752.png)

## Problem location
https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_policydev/apigw_polref/integrity_additional/index.html

## Suggestions for a fix
I have no idea how to fix that. The code looks good to me.

**Comment by alexearnshaw** [comment]
Thanks @cwiechmann  - this is actually a new bug in our Zoomin doc portal, it's been reported to them and we are awaiting a fix.

**Comment by alexearnshaw** [comment]
@cwiechmann This has finally been fixed by Zoomin.
