### ISSUE TITLE
[DOC] Publish Best practices for developers documentation

### ISSUE THREAD

**Issue by andreamussap** [Axway/axway-open-docs#339]
## Issue description

- Convert '[Best practices for developer documentation](https://techweb.axway.com/confluence/display/RDAPI/Best+practices+for+developer+documentation)' from Confluence to Markdown
- Publish the best practices under the Contribution Guidelines
- Share it with TWs Guild.

**Comment by alexearnshaw** [comment]
@andreamussap Just a reminder that this is one of the issues we selected for this sprint so you don't forget about it :)
