### ISSUE TITLE
[WEBSITE] Make Feedback widget on netlify more visible

### ISSUE THREAD

**Issue by andreamussap** [Axway/axway-open-docs#383]
The request for feedback on our pages doesn't stand out, it has the same style of the headings so it can be missed by a reader. We should have a look on how to make it move visible.

![NetlifyRequestFeedback](https://user-images.githubusercontent.com/10401080/74332460-a9a34b00-4d8d-11ea-87ac-4a2f48da21a4.jpg)

**I've looked at other docs sites** - 

- [Docker](https://docs.docker.com/docker-for-mac/install/#where-to-go-next): the way the feedback widget is at the bottom it seems almost hidden for me. This didn't prevent them to get lots of hits! So maybe it's just my personal opinion.
- [Kubernetes](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-application/): although at the botton, but at least they've put some strong collor on the buttons, and the Create issue/ Edit page options are behind the feedback, so there's no way to miss the feedback buttons IMO.
- [Apigee](https://docs.apigee.com/api-platform/get-started/get-started) added both on top and bottom of the page, so impossible to miss it. They're using 5 stars though instead of yes/no

Two ideas from the top of my head are to add some color to the yes/no buttons (like k8s), or try '[CSS utilities](https://docsydocs.netlify.com/docs/adding-content/lookandfeel/#css-utilities)' and add a background collor to the widget.

**Comment by alexearnshaw** [comment]
> So maybe it's just my personal opinion.
LOL yes I think this should be fairly low priority for that reason. My personal opinion is that it's ok as is, as these widgets shouldn't be so intrusive that they are annoying...Additionally we know the site only has internal traffic for now, so results from this widget are going to be limited for this reason in any case.

>Two ideas from the top of my head are to add some color to the yes/no buttons (like k8s), or try 'CSS utilities' and add a background collor to the widget.

In terms of changing the styling, I'm not that familiar with CSS so would need to spend some time figuring out where in the Docsy theme code this widget is, and then how to actually change it in our layout overrides, so it's not a quick fix...Also any change to the styling would need to be done in such a way that it fits with the overall look and feel of the site. 

This could probably be a good issue for a front-end dev or web developer with some UX expertise to fix?
