### ISSUE TITLE
[DOC] Fix badly formatted doc page

### ISSUE THREAD

**Issue by alexearnshaw** [Axway/axway-open-docs#424]
## Issue description

Formatting of the page is messed up and the information is hard to read

## Problem location

https://axway-open-docs.netlify.com/docs/apigtw_devguide/custom_filter_extension_kit/#palette-category-for-jabber-filters

## Suggestions for a fix

Fix the formatting

**Comment by andreamussap** [comment]
@alexearnshaw the page looks fine to me, no bad formatting!??

**Comment by alexearnshaw** [comment]
> @alexearnshaw the page looks fine to me, no bad formatting. I don't know what happened but I think we can close this issue ??

I can't see anything wrong now either...we can close
