### ISSUE TITLE
Remove unnecessary blog categories in site and CMS

### ISSUE THREAD

**Issue by alexearnshaw** [Axway/axway-open-docs#426]
@alexearnshaw We could remove 3 sub menus under '[Blogs](https://deploy-preview-423--axway-open-docs.netlify.com/blog/)' (News, Product releases, Friends of doc). They're might be a bit confusing for contributors on the CMS menu IMHO (or at least rename them ??)

![blogsubmenus](https://user-images.githubusercontent.com/10401080/74817173-63ea0380-52f4-11ea-8e64-a25e38067df9.jpg)

_Originally posted by @andreamussap in https://github.com/Axway/axway-open-docs/pull/423#issuecomment-588104387_

**Comment by andreamussap** [comment]
Closed - For more information, see RMF-187
