### ISSUE TITLE
[WEBSITE] Images missing on docs.axway.com

### ISSUE THREAD

**Issue by cwiechmann** [Axway/axway-open-docs#523]
## Issue description
❗️ Images included in our documentation are not visible when accessing the page under docs.axway.com. This is super important!

## Problem location
On many pages in general. Here is an example:
https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_installation/apigw_containers/container_intro/index.html
When hitting the same page in Netlify it works:
https://axway-open-docs.netlify.com/docs/apim_installation/apigw_containers/container_intro/index.html

## Suggestions for a fix
Root cause seems like a duplication of the path. The img source is rendered into the final HTML-Page like so on docs.axway.com:
`
https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_installation/apigw_containers/container_intro/-/bundle/axway-open-docs/page/images/containerguide/elastic_topology_arch.png
`
But it must be:
`
https://docs.axway.com/bundle/axway-open-docs/page/images/containerguide/elastic_topology_arch.png
`

**Comment by alexearnshaw** [comment]
@cwiechmann Thanks for reporting. This seems to be a regression introduced by Zoomin since they updated production last weekend :(
Andrea has opened a high priority ticket with Zoomin.
We have discovered that refreshing the page seems to fix the problem (but of course our customers will not know this!)

**Comment by rsavajiyani** [comment]
Hi @cwiechmann / @alexearnshaw, I am seeing the same issue with my recent addition to the Amplify Central docs, which was an update to the Add Environment docs page.

On the Netlify preview, the screenshots I added under "Add Your Environment to API Central", "Add V7 Environment", and "Add Kubernetes Environment" are rendering properly
https://deploy-preview-514--axway-open-docs.netlify.com/docs/central/add_env/

![netlify-preview](https://user-images.githubusercontent.com/30732073/77335109-f52d0b00-6ce2-11ea-821e-6bece791b161.png)

However, those same screenshots are not rendering on the docs.axway portal:

![axway-docs-add-env](https://user-images.githubusercontent.com/30732073/77335165-08d87180-6ce3-11ea-8e21-79692d79a84d.png)

I spoke to @andreamussap about this and she informed me about this issue. I'm located in Axway's Phoenix, Arizona office.

**Comment by cwiechmann** [comment]
@andreamussap, @alexearnshaw - Is there any ETA when this issue will be fixed?

**Comment by andreamussap** [comment]
@cwiechmann I've opened this ticket on Zoomin support - [ST-2287 Images sometimes not rendering in AMPLIFY API Management 7.7 and AMPLIFY Central docs](https://zoomin-software.atlassian.net/servicedesk/customer/portal/2/ST-2287). @lorentzpb  has mentioned you in a comment there. I believe that as Axway employee you can access that ticket.

**Comment by cwiechmann** [comment]
@andreamussap, looks like I can't access the ticket. Created an account using my Axway mail-address, but no access with that either.

**Comment by andreamussap** [comment]
@lorentzpb you've mentioned Chris on Zooming platform, but he's not able to see it. Chris, FYI this is the note Paul left there ->

> @cwiechmann Thanks for reporting. This seems to be a regression introduced by Zoomin since they updated production last weekend :(
> Andrea has opened a high priority ticket with Zoomin.
> We have discovered that refreshing the page seems to fix the problem (but of course our customers will not know this!)

**Comment by andreamussap** [comment]
**FIXED**.

Zoomin has fixed the issue. I've tested all URL above and another couple of pages, and all the images loaded correctly. Issue is tracked here https://zoomin-software.atlassian.net/servicedesk/customer/portal/2/ST-2287 (requires Zoomin authorization and login).

 Thank you @cwiechmann for reporting this.
