### ISSUE TITLE
[WEBSITE] Update the link of Learm more button on Netlify home page

### ISSUE THREAD

**Issue by andreamussap** [Axway/axway-open-docs#532]
## Issue description

Update the link of '**Learm more**' button on [Netlify home page](https://axway-open-docs.netlify.com/). This button takes you to the main docs landing page, the same page that you see when you click '**Documentation**' button on the top menu.

## Problem location

[Netlify home page](https://axway-open-docs.netlify.com/)

## Suggestions for a fix

Some options I can think from the top of my head:

- Remove it
- Label it as 'Documentation', since it links to the docs
- Create a page/text explaining more about what's this open source documentation
- Link to the Contribution Guidelines

**Comment by alexearnshaw** [comment]
@andreamussap I don't think you need to "pin" an issue to stop it getting marked as stale, you just need to add a "pinned" label I think? Pinning the issue puts it on top above the issues board (I didn't even know you could do that?!) :)

**Comment by andreamussap** [comment]
Closed - See RMF-187
