### ISSUE TITLE
Error when saving changes on Netlify CMS - Failed to load entry

### ISSUE THREAD

**Issue by andreamussap** [Axway/axway-open-docs#558]
This issue is to follow-up with '[Error when saving changes on Netlify CMS - Failed to load entry #3506](https://github.com/netlify/netlify-cms/issues/3506)' created on Netlify project.

### To Reproduce

* From [Axway Open Documentation](https://axway-open-docs.netlify.com/docs) navigate to any page and click **Edit on Netlify CMS** (top-right corner).
* When on Netlify CMS make any change and click **Save**
* CMS throws error ->

> Failed to load entry: TypeError: Cannot destruct property 'path' of 'o.filter(...).map(...)[0]' sa it is undefined.

**Comment by andreamussap** [comment]
@ygeorgiev-axway FIY

**Comment by andreamussap** [comment]
@alexearnshaw

- Netlify CMS issue #3506 is closed.
- There are many [releases in Netlify CMS](https://github.com/netlify/netlify-cms/releases) project today.
- Yasen told me that he was able to click the **Workflow** button and it worked
- Should we ask J B to test if CMS is working for him?

**Comment by alexearnshaw** [comment]
@jmbermingham Can you try the using the CMS today and let us know if the errors you were seeing yesterday are gone and you can edit pages successfully and send them for review?

**Comment by jmbermingham** [comment]
OK, I'll check it now.

**Comment by jmbermingham** [comment]
![Screenshot 2020-04-02 09 03 46](https://user-images.githubusercontent.com/60106408/78224716-edc6e800-74c0-11ea-8d29-84c0b25b7210.png)

Tried deleting the repo again and going back in, but this is what I see. 
Previous changes saved and I can't mark for review, only duplicate?

**Comment by andreamussap** [comment]
I spoke with @jmbermingham  this morning and it looks that the CMS edition is working for him now. Any new issue, he will let us know.
