### ISSUE TITLE
API Gateway and OpenID Connect

### ISSUE THREAD

**Issue by JohnD-Axway** [Axway/axway-open-docs#679]
This document should have a section on Supported grants/flow, a request from a customer came in on whether or not we support the Hybrid Flow:
https://openid.net/specs/openid-connect-core-1_0.html#HybridFlowAuth

We do support it but is not apparent from the doc.

**Comment by JohnD-Axway** [comment]
@alexearnshaw I'm just trying out creating an issue on the docs repo.
I assume I should create a related internal ticket in Jira?

**Comment by alexearnshaw** [comment]
@JohnD-Axway yes if you need to track the issue internally as part of a product release.

**Comment by JohnD-Axway** [comment]
Just bumping this to prevent closure.

**Comment by andreamussap** [comment]
Closed - See RMF-187
