### ISSUE TITLE
[DOC] Add info on installing git-secrets when running locally

### ISSUE THREAD

**Issue by alexearnshaw** [Axway/axway-open-docs#707]
## Issue description

Add info for maintainers and contributors to ask them to install git-secrets to prevent accidental exposure of sensitive info in commits. More details in Jira https://jira.axway.com/browse/RDTOOLSSUP-4772

## Problem location

https://axway-open-docs.netlify.app/docs/contribution_guidelines/setup_work_locally/

**Comment by andreamussap** [comment]
Test the procedure, see comments on https://jira.axway.com/browse/RDTOOLSSUP-4772
