### ISSUE TITLE
[DOC] Add video links to API Portal administration docs

### ISSUE THREAD

**Issue by alexearnshaw** [Axway/axway-open-docs#729]
## Issue description

Add the following videos to API Portal installation documentation:

- How to use tags and configuration settings to organize assets in the API catalog
- OAS3 support in API Portal
- How to run multiple sites on a single API Portal
- Demo | API Portal Troubleshooting
- Demo | Configure API Portal – Public API Mode Part 1 (Also part 2, Also part 3)
- How to optimize the API details displayed in the API catalog
- How to optimize the data shown in the API catalog

## Problem location

Various pages in API Portal Administration section 

## Suggestions for a fix

Video links and pages where they need to be added are detailed in https://techweb.axway.com/confluence/display/RDAPI/YouTube+video+review

**Comment by andreamussap** [comment]
Closed - See RMF-187
