### ISSUE TITLE
Prevent Netlify builds for CMS when the contributor has write access

### ISSUE THREAD

**Issue by alexearnshaw** [Axway/axway-open-docs#791]
When a contributor has write access the Netlify CMS uses the editorial workflow (and not open authoring workflow), which creates the pull request as soon as the draft is saved.

https://www.netlifycms.org/docs/configuration-options#publish-mode

This results in a Netlify build being triggered every time the contributor saves, instead of when they set the page to In Review status.

This ticket is to find out if these builds can be disabled somehow until the status is set to In Review.

More info from Netlify here https://community.netlify.com/t/support-guide-how-can-i-optimize-my-netlify-build-time/3907

**Comment by andreamussap** [comment]
Closed - For more information, see RMF-187
