### ISSUE TITLE
Stoplight in text and diagrams

### ISSUE THREAD

**Issue by matto2** [Axway/axway-open-docs#823]
It's not clear if Stoplight, (and other partners) is a requirement or just a suggestion/example

**Comment by alexearnshaw** [comment]
Thanks @matto2 
Do you mean in the API management overview section e.g. https://axway-open-docs.netlify.app/docs/api_mgmt_overview/api_mgmt_components/stoplight/ or in other places in the docs? 
@cwiechmann any comment on this? Can we make it clearer somehow?

**Comment by cwiechmann** [comment]
@matto2, Stoplight is optional.
@alexearnshaw, perhaps we should make that fact more clearer, that Stoplight is only one option. As long as it's based on OpenAPI 3.0, Swagger 2.0, 1.2, 1.1 we can integrate with any Design-Tool.

**Comment by cwiechmann** [comment]
Added an explanation on the lifecycle overview and in the tools page.
