### ISSUE TITLE
[DOC] Install php-zip centOS

### ISSUE THREAD

**Issue by anis-azzabi** [Axway/axway-open-docs#852]
## Issue description
Install php dependencies centOS

I ran the command 
`sudo yum install php php-cli php-common php-gd php-json php-intl php-mbstring php-mysqlnd php-pdo php-xml php-zip` 
When I ran 
`sh apiportal_install.sh` 
The error explains that php-zip is not installed 
After that, I ran 
`php -m`
It didn't display the php-zip module 
## Problem location

https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_installation/apiportal_install/install_dependencies/index.html
## Suggestions for a fix

I tried this command 
`sudo yum -y install php-pecl-zip`
The installation was successfull and when I found that php-zip module is installed

**Comment by alexearnshaw** [comment]
@andreamussap Can you discuss this issue with API Portal team and validate what change needs to be made to the doc for correctly installing php-zip?

**Comment by andreamussap** [comment]
@anis-azzabi The issue is fixed via PR #860 . Thank you!!
