### ISSUE TITLE
[WEBSITE] Add copy to clipboard button to code samples

### ISSUE THREAD

**Issue by alexearnshaw** [Axway/axway-open-docs#877]
## Issue description

We've received user feedback that code samples should have a "Copy" button to copy the code to the clipboard.

## Problem location

Code samples

## Suggestions for a fix

Hugo doesn't support this out of the box but a Google search offers many options to implement this using Javascript, for example https://aaronluna.dev/blog/add-copy-button-to-code-blocks-hugo-chroma/

Also worth asking the Docsy theme maintainers to add this. (https://github.com/google/docsy/issues/292)

**Comment by andreamussap** [comment]
Closed - For more information, see RMF-187
