### ISSUE TITLE
[WEBSITE] AMPLIFY Central and Integration Builder not clickable

### ISSUE THREAD

**Issue by cwiechmann** [Axway/axway-open-docs#891]
## Issue description

On the page mentioned below, the title of the tiles AMPLIFY Central & Integration Builder are not clickable, while all other tiles are.

## Problem location

https://docs.axway.com/category/platform

## Suggestions for a fix

Make the titles clickable as well.

**Comment by andreamussap** [comment]
This is fixed. For more information, see RMF-187
