### ISSUE TITLE
[DOC] Broken links in Connect API Manager docs

### ISSUE THREAD

**Issue by ingo** [Axway/axway-open-docs#928]
## Issue description
https://github.com/Axway/axway-open-docs/blame/master/content/en/docs/central/connect-api-manager/prepare-amplify-central.md#L107 is a 404 (the link to the "Manage an environment using AMPLIFY CLI")

## Problem location
https://github.com/Axway/axway-open-docs/blame/master/content/en/docs/central/connect-api-manager/prepare-amplify-central.md#L107

## Suggestions for a fix
Unsure the proper location.

**Comment by alexearnshaw** [comment]
@ingo Thanks for reporting and sorry for the delay, we were on a training course last week.

@lbadenhop @cbordier I can confirm there are at least 2 broken links in the page https://axway-open-docs.netlify.app/docs/central/connect-api-manager/prepare-amplify-central/, can one of you address this please? I'll assign to Lisa for now.

If you are running locally you can use a npm package blc to check for broken links to avoid this issue in future. More details here https://techweb.axway.com/confluence/display/RDAPI/Process+to+review+pull+requests#Processtoreviewpullrequests-Runbrokenlinkcheckerlocally

**Comment by lbadenhop** [comment]
@alexearnshaw, @cbordier Thanks. I'll take care f this today.

**Comment by cbordier** [comment]
@lbadenhop ,
This is the real link we should point to: 
- Manage an API proxy using AMPLIFY CLI: https://docs.axway.com/bundle/axway-open-docs/page/docs/central/cli_central/cli_install/index.html
- Manage an environment using AMPLIFY CLI: https://docs.axway.com/bundle/axway-open-docs/page/docs/central/cli_central/cli_environments/index.html

**Comment by lbadenhop** [comment]
@alexearnshaw This issue was fixed with #941
